### PR TITLE
movie, episode resume points  … with user defined select action.

### PR DESCRIPTION
**Pull request by Lunatixz**
I noticed a request for support in the forums, so I figured i'd help out :) 
Initial support for tag queries, works with movies and tvshows.

I'd like to add skin support so tags have their own result row, however this might be a issue? Since it requires all dependent skins to update. 

I'm leaning towards a alternative approach, similar to how you mark "watched" media with a icon... 

Your feedback would be appreciated.

### CODE REVIEW

**Comment by Lunatixz** [comment]
While waiting for your feedback on tags... I also added resume points to Movie searches, It can be added to all content types. Let me know if the code is acceptable.

**Comment by Lunatixz** [comment]
I'm going to move forward with tags and resume points... 

My plan is to wrap the new "tag" control id's in a exception. This way skinners don't have to upgrade right away.

I'll also expand resume points to include tv episodes.

Hope all is well.

**Comment by ronie** [comment]
thanx for the code @Lunatixz ! 
much appreciated :-)

wrapping new controls in a try/except clause is indeed the only way to prevent the addon from crashing
with skins that haven't been updated yet.

that being said, i'm not really sold on the idea to add support for tag search...
one can simply browse to the tag node in the videolibrary to get a list of movies belonging to a certain tag instead.

i've had similar requests in the past (search by genre, director, etc..) which never made it in either.
i feel i we add one of them, we should be adding all, and i don't see a sensible way of supporting all that. 


the resume stuff is neat though. it would be nice if you could make it respect the 'Default select action' from the kodi settings.

**Comment by Lunatixz** [comment]
I understand your concern, tags can open the door to all other search parameters.  I'm not all that familiar with tags. My only insight would be tags are user created? whereas genres are for the most part automatic. So perhaps it wouldn't be bad to add tags and stop there? It's your call...

Resume points are cool, that was another feature request I saw in the forums. As you can see it's fairly easy to execute, but i'm not sure if the "Default selection action"user preference is available via json? I'll have to look into that.

Another feature i'd like to run by you... Plugin content search? yay or nay? I think this could be cool. I have a lot of experience with this type of json parsing. I believe with a little magic users can find what they want. I envision a simple user query like "Vevo: Radio Head" Vevo being the plugin to search.

Let me know what you think, as always thanks for your tireless work with Kodi... its very appreciated.

**Comment by ronie** [comment]
yeah, i think we should shelve the tag search idea for now.
perhaps in a future version someone may come up with a smart way to implement all of the search options people have asked for.
maybe i'll even split the addon into a basic mode (as it is now) and and extended one that provides more capabilities...

while i haven't tested it, there's a json method to retrieve settings.
sadly our wiki docs aren't up-to-date and this method isn't listed there.
but if you enable the webserver in kodi and load http://localhost:8081/jsonrpc in your browser,
you should be enable to find it. (Settings.GetSetting or something like that...)

plugin search sounds cool, but my only concern is it might turn this addon into the ultimate piracy search tool.
that being said, i have to admit that i am curious about what kind of 'magic' is needed in order to search for plugin content.

**Comment by Lunatixz** [comment]
okay i'll drop tags and push a new branch with resume points only....

As for plugin content, piracy was my concern as well... I don't mind dropping the idea.

BTW by 'magic' i'm just being dramatic about some fuzzy logic i've used in the past to help retrieve wanted results.... just some regex wizardry nothing more. Rabbits out of the hat :)

Can you point me in the direction of some Kodi projects that need help?

**Comment by Lunatixz** [comment]
We can close this request, I'll open a new one with resume points only

**Comment by Lunatixz** [comment]
Sorry figured its easier to keep this open and update it... I started clean and added resume points for movies and episodes with user default action.

**Comment by Lunatixz** [comment]
How would you like to handle "show information" select action?
https://github.com/ronie/script.globalsearch/pull/5/files#diff-3bb231094e57080a42410574e2044978R894

**Comment by ronie** [comment]
perhaps just leave it as is for now.
i'm kind of waiting for this to be merged:
https://github.com/xbmc/xbmc/pull/10616

that will allow addons to open the standard videoinfodialog.
much easier than the custom info dialog i have now in this addon.

**Comment by ronie** [comment]
> Can you point me in the direction of some Kodi projects that need help?

just work on things you like to work on :-)

that what we all do and what keeps us motivated, there's no point in telling people to work on something they might not be interested in.

**Comment by Lunatixz** [comment]
xbmc/xbmc#10616 looks great...

> just work on things you like to work on :-)

I was hoping to finish the keymap plugin... I believe there is a demand for it. If we can unify script keymaps we can minimize user disturbances while advocating a healthier, cleaner repository free from "hacky" code.

I'm 100% on board with your opinion... it should be part of the core code. However I don't see this happening for at least the next two/three Kodi versions.

If you can discuss this internally i'd appreciate it... If the team is game for a plugin handling it... I'll finish the project.

Kevin

**Comment by Lunatixz** [comment]
Moved to #6

**Pull request closed without merging**
